### ISSUE TITLE
`PUT /teams/{teamId}/sprints/{sprintId}/meeting`

### ISSUE THREAD

**Issue by FEgor04** [FEgor04/is-course-work#127]
Создает встречу с указанным типом в данном спринте.
Тип может быть один из `retro`, `review`, `planning`

Если спринт такого типа уже существует - перезаписать его

**Comment by forafox** [comment]
Предложено не реализовывать эту ручку, потому что есть PUT запрос на изменение всего спринта (включая даты митинга)

Обсудили, закрываю
