### ISSUE TITLE
`POST /products`

### ISSUE THREAD

**Issue by FEgor04** [FEgor04/is-course-work#5]
This endpoints creates new product, sets principal as its owner. Request accepts only title & description

**Comment by forafox** [comment]
> This endpoints creates new product, sets principal as its owner. Request accepts only title & description

 Request accepts only title & description AND shortName???

**Comment by FEgor04** [comment]
> > This endpoints creates new product, sets principal as its owner. Request accepts only title & description
> 
> Request accepts only title & description AND shortName???

`title` = `shortName`? например у нас `title` = ThreeBaristas, `description` = "Мы заниаемся пинанием чего не попадя ..."

Давай для консистентности называть все `title`

**Comment by forafox** [comment]
Решили оставить
title
description
ticker (Not null)
