### ISSUE TITLE
Реализация Spring Security с использованием jwt токенов

### ISSUE THREAD

**Issue by forafox** [FEgor04/is-course-work#85]

**Comment by FEgor04** [comment]
Опиши, пожалуйста, скоуп задачи.
Включает ли она в себя написание эндпоинтов для входа, регистрации и обновления токена?
Относится ли к эпику #61 ?

**Comment by forafox** [comment]
@FEgor04 
1. Будет доступен swagger
2. Будут написаны эндпоинты для входа, регистрации, гетми, рефреша токена
3. Да, относится, но только со стороны бэка. Полностью задачу не перекроет. Получение юзеров сделано не будет
